plugins {
	id "java-module"
	id "maven-publish"
}


publishing {
	publications {
		publishedArtifacts( MavenPublication ) {
			from components.java
			pom {
				name = "Hibernate Accessor"
				description = "A library that generalizes field/property access and instance creation across Hibernate projects"
				url = "https://github.com/hibernate/hibernate-accessor"

				organization {
					name = 'Hibernate.org'
					url = 'https://hibernate.org'
				}

				licenses {
					license {
						name = "Apache License Version 2.0"
						url = "http://www.apache.org/licenses/"
						distribution = "repo"
					}
				}

				scm {
					url = "https://github.com/hibernate/hibernate-accessor"
					connection = "scm:git:https://github.com/hibernate/hibernate-accessor.git"
					developerConnection = "scm:git:https://github.com/hibernate/hibernate-accessor.git"
				}

				issueManagement {
					system = "github"
					url = "https://github.com/hibernate/hibernate-accessor"
				}

				developers {
					developer {
						id = "hibernate-team"
						name = "The Hibernate Development Team"
						organization = "Hibernate.org"
						organizationUrl = "https://hibernate.org"
					}
				}

			}
		}
	}
	repositories {
		maven {
			name = 'staging'
			url = rootProject.layout.buildDirectory.dir("staging-deploy${File.separator}maven")
		}
	}
}

tasks.register("releasePrepare") {
	dependsOn publishAllPublicationsToStagingRepository
}
