sonar.projectName=Hibernate Accessor
sonar.projectDescription=A library that generalizes field/property access and instance creation across Hibernate projects.

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.modules=hibernate-accessor,hibernate-accessor-asm,hibernate-accessor-bytebuddy,\
	hibernate-accessor-tck,\
	hibernate-accessor-tck-reflection,hibernate-accessor-tck-methodhandle,\
	hibernate-accessor-tck-lambda,hibernate-accessor-tck-asm,\
	hibernate-accessor-tck-bytebuddy

hibernate-accessor.sonar.projectName=Hibernate Accessor - Core
hibernate-accessor.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor
hibernate-accessor.sonar.sources=src/main/java
hibernate-accessor.sonar.java.binaries=build/classes/java/main

hibernate-accessor-asm.sonar.projectName=Hibernate Accessor - Accessor ASM
hibernate-accessor-asm.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-asm
hibernate-accessor-asm.sonar.sources=src/main/java
hibernate-accessor-asm.sonar.java.binaries=build/classes/java/main

hibernate-accessor-bytebuddy.sonar.projectName=Hibernate Accessor - Accessor ByteBuddy
hibernate-accessor-bytebuddy.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-bytebuddy
hibernate-accessor-bytebuddy.sonar.sources=src/main/java
hibernate-accessor-bytebuddy.sonar.java.binaries=build/classes/java/main

hibernate-accessor-tck.sonar.projectName=Hibernate Accessor - Accessor TCK
hibernate-accessor-tck.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-tck
hibernate-accessor-tck.sonar.sources=
hibernate-accessor-tck.sonar.tests=src/main/java
hibernate-accessor-tck.sonar.java.binaries=build/classes/java/main

hibernate-accessor-tck-reflection.sonar.projectName=Hibernate Accessor - Accessor TCK Reflection
hibernate-accessor-tck-reflection.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-tck-reflection
hibernate-accessor-tck-reflection.sonar.sources=
hibernate-accessor-tck-reflection.sonar.tests=src/test/java
hibernate-accessor-tck-reflection.sonar.java.binaries=build/classes/java/test

hibernate-accessor-tck-methodhandle.sonar.projectName=Hibernate Accessor - Accessor TCK MethodHandle
hibernate-accessor-tck-methodhandle.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-tck-methodhandle
hibernate-accessor-tck-methodhandle.sonar.sources=
hibernate-accessor-tck-methodhandle.sonar.tests=src/test/java
hibernate-accessor-tck-methodhandle.sonar.java.binaries=build/classes/java/test

hibernate-accessor-tck-lambda.sonar.projectName=Hibernate Accessor - Accessor TCK Lambda
hibernate-accessor-tck-lambda.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-tck-lambda
hibernate-accessor-tck-lambda.sonar.sources=
hibernate-accessor-tck-lambda.sonar.tests=src/test/java
hibernate-accessor-tck-lambda.sonar.java.binaries=build/classes/java/test

hibernate-accessor-tck-asm.sonar.projectName=Hibernate Accessor - Accessor TCK ASM
hibernate-accessor-tck-asm.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-tck-asm
hibernate-accessor-tck-asm.sonar.sources=
hibernate-accessor-tck-asm.sonar.tests=src/test/java
hibernate-accessor-tck-asm.sonar.java.binaries=build/classes/java/test

hibernate-accessor-tck-bytebuddy.sonar.projectName=Hibernate Accessor - Accessor TCK ByteBuddy
hibernate-accessor-tck-bytebuddy.sonar.projectBaseDir=hibernate-accessor/hibernate-accessor-tck-bytebuddy
hibernate-accessor-tck-bytebuddy.sonar.sources=
hibernate-accessor-tck-bytebuddy.sonar.tests=src/test/java
hibernate-accessor-tck-bytebuddy.sonar.java.binaries=build/classes/java/test
