plugins {
    id 'jacoco-report-aggregation'
}

description = 'Reporting module'

dependencies {
	jacocoAggregation project(':hibernate-accessor')
	jacocoAggregation project(':hibernate-accessor-asm')
	jacocoAggregation project(':hibernate-accessor-bytebuddy')
}

tasks.register('mergeCodeCoverageReport', JacocoReport) {
    executionData fileTree(rootProject.layout.projectDirectory.asFile).include("**/build/jacoco/*.exec")

	sourceSets project(':hibernate-accessor').sourceSets.main
	sourceSets project(':hibernate-accessor-asm').sourceSets.main
	sourceSets project(':hibernate-accessor-bytebuddy').sourceSets.main

    reports {
        xml.required = true
    }

    dependsOn rootProject.subprojects.collect { p -> p.tasks.matching { it.name == 'compileJava' } }
}
