/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright: Hibernate Authors. See AUTHORS.txt.
 */
package org.hibernate.accessor.classfile.impl;

import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodType;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Map;

import io.smallrye.classfile.ClassFileVersion;
import io.smallrye.classfile.CodeBuilder;
import io.smallrye.classfile.Label;

final class ClassFileUtils {
	private static final ClassDesc[] NO_PARAM_DESCS = new ClassDesc[0];

	static final ClassDesc CD_EXCEPTION = ClassDesc.of( "org.hibernate.accessor.AccessorException" );
	/**
	 * The {@code byte[]} array descriptor ({@code [B}).
	 */
	static final ClassDesc CD_BYTE_ARRAY = ConstantDescs.CD_byte.arrayType();
	/**
	 * The name of every constructor, as used in the constant pool.
	 */
	static final String CONSTRUCTOR_NAME = "<init>";

	/**
	 * The special name of class initialization methods, {@value}.
	 */
	public static final String CLASS_INIT_NAME = "<clinit>";

	/**
	 * The class-file major version (Java 17) emitted for generated classes.
	 * <p>
	 * Pinned to the project baseline rather than derived from the running JVM so that
	 * generated bytecode is deterministic across environments; it must stay at or below
	 * any JDK on which the generated classes may be loaded.
	 */
	static final ClassFileVersion GENERATED_CLASS_MAJOR_VERSION = ClassFileVersion.of( 61, 0 );

	private static final Map<Class<?>, BoxingInfo> BOXING = Map.of(
			boolean.class, new BoxingInfo( ClassDesc.of( "java.lang.Boolean" ), ConstantDescs.CD_boolean, "booleanValue", methodTypeDesc( ConstantDescs.CD_boolean ) ),
			byte.class, new BoxingInfo( ClassDesc.of( "java.lang.Byte" ), ConstantDescs.CD_byte, "byteValue", methodTypeDesc( ConstantDescs.CD_byte ) ),
			char.class, new BoxingInfo( ClassDesc.of( "java.lang.Character" ), ConstantDescs.CD_char, "charValue", methodTypeDesc( ConstantDescs.CD_char ) ),
			short.class, new BoxingInfo( ClassDesc.of( "java.lang.Short" ), ConstantDescs.CD_short, "shortValue", methodTypeDesc( ConstantDescs.CD_short ) ),
			int.class, new BoxingInfo( ClassDesc.of( "java.lang.Integer" ), ConstantDescs.CD_int, "intValue", methodTypeDesc( ConstantDescs.CD_int ) ),
			long.class, new BoxingInfo( ClassDesc.of( "java.lang.Long" ), ConstantDescs.CD_long, "longValue", methodTypeDesc( ConstantDescs.CD_long ) ),
			float.class, new BoxingInfo( ClassDesc.of( "java.lang.Float" ), ConstantDescs.CD_float, "floatValue", methodTypeDesc( ConstantDescs.CD_float ) ),
			double.class, new BoxingInfo( ClassDesc.of( "java.lang.Double" ), ConstantDescs.CD_double, "doubleValue", methodTypeDesc( ConstantDescs.CD_double ) )
	);

	private static final Map<Class<?>, List<Class<?>>> WIDENING_SOURCES = Map.of(
			short.class, List.of( byte.class ),
			int.class, List.of( byte.class, short.class, char.class ),
			long.class, List.of( byte.class, short.class, char.class, int.class ),
			float.class, List.of( byte.class, short.class, char.class, int.class, long.class ),
			double.class, List.of( byte.class, short.class, char.class, int.class, long.class, float.class )
	);

	private ClassFileUtils() {
	}

	static ClassDesc classDesc(Class<?> type) {
		return ClassDesc.ofDescriptor( type.descriptorString() );
	}

	/**
	 * Builds the {@link ClassDesc} for a generated (top-level) class from its internal name.
	 */
	static ClassDesc generatedClassDesc(String internalName) {
		return ClassDesc.ofDescriptor( "L" + internalName + ";" );
	}

	static MethodTypeDesc methodTypeDesc(Method method) {
		return MethodTypeDesc.ofDescriptor(
				MethodType.methodType( method.getReturnType(), method.getParameterTypes() ).descriptorString()
		);
	}

	static MethodTypeDesc methodTypeDesc(ClassDesc classDesc) {
		return MethodTypeDesc.of( classDesc, NO_PARAM_DESCS );
	}

	static MethodTypeDesc constructorTypeDesc(Constructor<?> constructor) {
		return MethodTypeDesc.ofDescriptor(
				MethodType.methodType( void.class, constructor.getParameterTypes() ).descriptorString()
		);
	}

	static void emitBox(CodeBuilder cb, Class<?> type) {
		BoxingInfo info = BOXING.get( type );
		if ( info != null ) {
			cb.invokestatic( info.wrapperDesc, "valueOf", info.valueOfType() );
		}
	}

	static void emitUnboxOrCast(CodeBuilder cb, Class<?> type) {
		BoxingInfo info = BOXING.get( type );
		if ( info != null ) {
			cb.checkcast( info.wrapperDesc );
			cb.invokevirtual( info.wrapperDesc, info.unboxMethod, info.unboxType );
		}
		else {
			cb.checkcast( classDesc( type ) );
		}
	}

	static void emitWideningUnbox(CodeBuilder cb, Class<?> type) {
		List<Class<?>> sources = WIDENING_SOURCES.get( type );
		if ( sources == null ) {
			emitUnboxOrCast( cb, type );
			return;
		}

		BoxingInfo target = BOXING.get( type );
		Label end = cb.newLabel();

		Label notExact = cb.newLabel();
		cb.dup();
		cb.instanceOf( target.wrapperDesc );
		cb.ifeq( notExact );
		cb.checkcast( target.wrapperDesc );
		cb.invokevirtual( target.wrapperDesc, target.unboxMethod, target.unboxType );
		cb.goto_( end );
		cb.labelBinding( notExact );

		for ( Class<?> source : sources ) {
			BoxingInfo si = BOXING.get( source );
			Label skip = cb.newLabel();
			cb.dup();
			cb.instanceOf( si.wrapperDesc );
			cb.ifeq( skip );
			cb.checkcast( si.wrapperDesc );
			cb.invokevirtual( si.wrapperDesc, si.unboxMethod, si.unboxType );
			emitPrimitiveWidening( cb, source, type );
			cb.goto_( end );
			cb.labelBinding( skip );
		}

		cb.pop();
		emitThrow( cb, "Cannot convert value to primitive type '" + type.getName() + "'" );

		cb.labelBinding( end );
	}

	private static void emitPrimitiveWidening(CodeBuilder cb, Class<?> source, Class<?> target) {
		if ( source == long.class ) {
			if ( target == float.class ) {
				cb.l2f();
			}
			else if ( target == double.class ) {
				cb.l2d();
			}
		}
		else if ( source == float.class ) {
			if ( target == double.class ) {
				cb.f2d();
			}
		}
		else {
			if ( target == long.class ) {
				cb.i2l();
			}
			else if ( target == float.class ) {
				cb.i2f();
			}
			else if ( target == double.class ) {
				cb.i2d();
			}
		}
	}

	static void emitIntConstant(CodeBuilder cb, int value) {
		if ( value >= -1 && value <= 5 ) {
			cb.loadConstant( value );
		}
		else if ( value >= Byte.MIN_VALUE && value <= Byte.MAX_VALUE ) {
			cb.bipush( value );
		}
		else if ( value >= Short.MIN_VALUE && value <= Short.MAX_VALUE ) {
			cb.sipush( value );
		}
		else {
			cb.loadConstant( value );
		}
	}

	static void emitThrow(CodeBuilder cb, String message) {
		cb.new_( CD_EXCEPTION );
		cb.dup();
		cb.loadConstant( message );
		cb.invokespecial( CD_EXCEPTION, CONSTRUCTOR_NAME, MethodTypeDesc.of( ConstantDescs.CD_void, ConstantDescs.CD_String ) );
		cb.athrow();
	}

	private record BoxingInfo(ClassDesc wrapperDesc, ClassDesc primitiveDesc, String unboxMethod, MethodTypeDesc unboxType) {
		MethodTypeDesc valueOfType() {
			return MethodTypeDesc.of( wrapperDesc, primitiveDesc );
		}
	}
}
